/*
* Copyright 2013 by the digital.me project (http://www.dime-project.eu).
*
* Licensed under the EUPL, Version 1.1 only (the "Licence");
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
*
* http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and limitations under the Licence.
*/

package eu.dime.ps.semantic.model.dcon;

import org.ontoware.aifbcommons.collection.ClosableIterator;
import org.ontoware.rdf2go.exception.ModelRuntimeException;
import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.Base;
import org.ontoware.rdfreactor.runtime.ReactorResult;


/**
 * This class manages access to these properties:
 * <ul>
 *   <li> AdHocGroup </li>
 *   <li> NearbyPerson </li>
 * </ul>
 *
 * class- This class was generated by <a href="http://RDFReactor.semweb4j.org">RDFReactor</a> */
public class Peers extends eu.dime.ps.semantic.model.dcon.Aspect {

    /** http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#Peers */
    @SuppressWarnings("hiding")
	public static final URI RDFS_CLASS = new URIImpl("http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#Peers", false);

    /** http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#adHocGroup */
    @SuppressWarnings("hiding")
	public static final URI ADHOCGROUP = new URIImpl("http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#adHocGroup",false);

    /** http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#nearbyPeer */
    @SuppressWarnings("hiding")
	public static final URI NEARBYPERSON = new URIImpl("http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#nearbyPerson",false);

    /** 
     * All property-URIs with this class as domain.
     * All properties of all super-classes are also available. 
     */
    @SuppressWarnings("hiding")
    public static final URI[] MANAGED_URIS = {
      new URIImpl("http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#adHocGroup",false),
      new URIImpl("http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#nearbyPeer",false) 
    };


	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.semweb4j.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier Resource that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c1] 
	 */
	protected Peers (Model model, URI classURI, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param instanceIdentifier an RDF2Go Resource identifying this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c2] 
	 */
	public Peers (Model model, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}


	/**
	 * Returns a Java wrapper over an RDF object, identified by a URI, given as a String.
	 * Creating two wrappers for the same URI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uriString a URI given as a String
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 * @throws ModelRuntimeException if URI syntax is wrong
	 *
	 * [Generated from RDFReactor template rule #c7] 
	 */
	public Peers (Model model, String uriString, boolean write) throws ModelRuntimeException {
		super(model, RDFS_CLASS, new URIImpl(uriString,false), write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c8] 
	 */
	public Peers (Model model, BlankNode bnode, boolean write) {
		super(model, RDFS_CLASS, bnode, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly generated URI.
	 * Creating two wrappers results in different URIs.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c9] 
	 */
	public Peers (Model model, boolean write) {
		super(model, RDFS_CLASS, model.newRandomUniqueURI(), write);
	}

    ///////////////////////////////////////////////////////////////////
    // typing

	/**
	 * Return an existing instance of this class in the model. No statements are written.
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return an instance of Peers  or null if none existst
	 *
	 * [Generated from RDFReactor template rule #class0] 
	 */
	public static Peers  getInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getInstance(model, instanceResource, Peers.class);
	}

	/**
	 * Create a new instance of this class in the model. 
	 * That is, create the statement (instanceResource, RDF.type, http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#Peers).
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class1] 
	 */
	public static void createInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.createInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return true if instanceResource is an instance of this class in the model
	 *
	 * [Generated from RDFReactor template rule #class2] 
	 */
	public static boolean hasInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.hasInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as RDF resources
	 *
	 * [Generated from RDFReactor template rule #class3] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllInstances(Model model) {
		return Base.getAllInstances(model, RDFS_CLASS, org.ontoware.rdf2go.model.node.Resource.class);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as a ReactorResult,
	 * which can conveniently be converted to iterator, list or array.
	 *
	 * [Generated from RDFReactor template rule #class3-as] 
	 */
	public static ReactorResult<? extends Peers> getAllInstances_as(Model model) {
		return Base.getAllInstances_as(model, RDFS_CLASS, Peers.class );
	}

    /**
	 * Remove rdf:type Peers from this instance. Other triples are not affected.
	 * To delete more, use deleteAllProperties
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class4] 
	 */
	public static void deleteInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * Delete all (this, *, *), i.e. including rdf:type
	 * @param model an RDF2Go model
	 * @param resource
	 */
	public static void deleteAllProperties(Model model,	org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteAllProperties(model, instanceResource);
	}

    ///////////////////////////////////////////////////////////////////
    // property access methods

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as RDF resources, that have a relation 'Peers' to this Peers instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1static] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllPeers_Inverse(Model model, Object objectValue) {
		return Base.getAll_Inverse(model, eu.dime.ps.semantic.model.RDFReactorThing.PEERS, objectValue);
	}

	/**
	 * @return all A's as RDF resources, that have a relation 'Peers' to this Peers instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1dynamic] 
	 */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllPeers_Inverse() {
		return Base.getAll_Inverse(this.model, eu.dime.ps.semantic.model.RDFReactorThing.PEERS, this.getResource() );
	}

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as a ReactorResult, that have a relation 'Peers' to this Peers instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse-as1static] 
	 */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Resource> getAllPeers_Inverse_as(Model model, Object objectValue) {
		return Base.getAll_Inverse_as(model, eu.dime.ps.semantic.model.RDFReactorThing.PEERS, objectValue, org.ontoware.rdf2go.model.node.Resource.class);
	}



    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@10d5008d has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasAdHocGroup(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, ADHOCGROUP);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@10d5008d has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasAdHocGroup() {
		return Base.has(this.model, this.getResource(), ADHOCGROUP);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@10d5008d has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasAdHocGroup(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, ADHOCGROUP);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@10d5008d has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasAdHocGroup( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), ADHOCGROUP);
	}

     /**
     * Get all values of property AdHocGroup as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllAdHocGroup_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, ADHOCGROUP);
	}
	
    /**
     * Get all values of property AdHocGroup as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllAdHocGroup_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, ADHOCGROUP, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property AdHocGroup as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllAdHocGroup_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), ADHOCGROUP);
	}

    /**
     * Get all values of property AdHocGroup as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllAdHocGroup_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), ADHOCGROUP, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property AdHocGroup     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<eu.dime.ps.semantic.model.pimo.PersonGroup> getAllAdHocGroup(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, ADHOCGROUP, eu.dime.ps.semantic.model.pimo.PersonGroup.class);
	}
	
    /**
     * Get all values of property AdHocGroup as a ReactorResult of PersonGroup 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<eu.dime.ps.semantic.model.pimo.PersonGroup> getAllAdHocGroup_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, ADHOCGROUP, eu.dime.ps.semantic.model.pimo.PersonGroup.class);
	}

    /**
     * Get all values of property AdHocGroup     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<eu.dime.ps.semantic.model.pimo.PersonGroup> getAllAdHocGroup() {
		return Base.getAll(this.model, this.getResource(), ADHOCGROUP, eu.dime.ps.semantic.model.pimo.PersonGroup.class);
	}

    /**
     * Get all values of property AdHocGroup as a ReactorResult of PersonGroup 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<eu.dime.ps.semantic.model.pimo.PersonGroup> getAllAdHocGroup_as() {
		return Base.getAll_as(this.model, this.getResource(), ADHOCGROUP, eu.dime.ps.semantic.model.pimo.PersonGroup.class);
	}
 
    /**
     * Adds a value to property AdHocGroup as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addAdHocGroup(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, ADHOCGROUP, value);
	}
	
    /**
     * Adds a value to property AdHocGroup as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addAdHocGroup( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), ADHOCGROUP, value);
	}
    /**
     * Adds a value to property AdHocGroup from an instance of PersonGroup 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addAdHocGroup(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.pimo.PersonGroup value) {
		Base.add(model, instanceResource, ADHOCGROUP, value);
	}
	
    /**
     * Adds a value to property AdHocGroup from an instance of PersonGroup 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addAdHocGroup(eu.dime.ps.semantic.model.pimo.PersonGroup value) {
		Base.add(this.model, this.getResource(), ADHOCGROUP, value);
	}
  

    /**
     * Sets a value of property AdHocGroup from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setAdHocGroup( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, ADHOCGROUP, value);
	}
	
    /**
     * Sets a value of property AdHocGroup from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setAdHocGroup( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), ADHOCGROUP, value);
	}
    /**
     * Sets a value of property AdHocGroup from an instance of PersonGroup 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setAdHocGroup(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.pimo.PersonGroup value) {
		Base.set(model, instanceResource, ADHOCGROUP, value);
	}
	
    /**
     * Sets a value of property AdHocGroup from an instance of PersonGroup 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setAdHocGroup(eu.dime.ps.semantic.model.pimo.PersonGroup value) {
		Base.set(this.model, this.getResource(), ADHOCGROUP, value);
	}
  


    /**
     * Removes a value of property AdHocGroup as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeAdHocGroup( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, ADHOCGROUP, value);
	}
	
    /**
     * Removes a value of property AdHocGroup as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeAdHocGroup( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), ADHOCGROUP, value);
	}
    /**
     * Removes a value of property AdHocGroup given as an instance of PersonGroup 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeAdHocGroup(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.pimo.PersonGroup value) {
		Base.remove(model, instanceResource, ADHOCGROUP, value);
	}
	
    /**
     * Removes a value of property AdHocGroup given as an instance of PersonGroup 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeAdHocGroup(eu.dime.ps.semantic.model.pimo.PersonGroup value) {
		Base.remove(this.model, this.getResource(), ADHOCGROUP, value);
	}
  
    /**
     * Removes all values of property AdHocGroup     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllAdHocGroup( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, ADHOCGROUP);
	}
	
    /**
     * Removes all values of property AdHocGroup	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllAdHocGroup() {
		Base.removeAll(this.model, this.getResource(), ADHOCGROUP);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@be630d4 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasNearbyPerson(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, NEARBYPERSON);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@be630d4 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasNearbyPerson() {
		return Base.has(this.model, this.getResource(), NEARBYPERSON);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@be630d4 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasNearbyPerson(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, NEARBYPERSON);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@be630d4 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasNearbyPerson( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), NEARBYPERSON);
	}

     /**
     * Get all values of property NearbyPerson as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllNearbyPerson_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, NEARBYPERSON);
	}
	
    /**
     * Get all values of property NearbyPerson as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllNearbyPerson_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, NEARBYPERSON, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property NearbyPerson as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllNearbyPerson_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), NEARBYPERSON);
	}

    /**
     * Get all values of property NearbyPerson as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllNearbyPerson_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), NEARBYPERSON, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property NearbyPerson     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<eu.dime.ps.semantic.model.pimo.Person> getAllNearbyPerson(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, NEARBYPERSON, eu.dime.ps.semantic.model.pimo.Person.class);
	}
	
    /**
     * Get all values of property NearbyPerson as a ReactorResult of Person 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<eu.dime.ps.semantic.model.pimo.Person> getAllNearbyPerson_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, NEARBYPERSON, eu.dime.ps.semantic.model.pimo.Person.class);
	}

    /**
     * Get all values of property NearbyPerson     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<eu.dime.ps.semantic.model.pimo.Person> getAllNearbyPerson() {
		return Base.getAll(this.model, this.getResource(), NEARBYPERSON, eu.dime.ps.semantic.model.pimo.Person.class);
	}

    /**
     * Get all values of property NearbyPerson as a ReactorResult of Person 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<eu.dime.ps.semantic.model.pimo.Person> getAllNearbyPerson_as() {
		return Base.getAll_as(this.model, this.getResource(), NEARBYPERSON, eu.dime.ps.semantic.model.pimo.Person.class);
	}
 
    /**
     * Adds a value to property NearbyPerson as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addNearbyPerson(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, NEARBYPERSON, value);
	}
	
    /**
     * Adds a value to property NearbyPerson as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addNearbyPerson( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), NEARBYPERSON, value);
	}
    /**
     * Adds a value to property NearbyPerson from an instance of Person 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addNearbyPerson(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.pimo.Person value) {
		Base.add(model, instanceResource, NEARBYPERSON, value);
	}
	
    /**
     * Adds a value to property NearbyPerson from an instance of Person 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addNearbyPerson(eu.dime.ps.semantic.model.pimo.Person value) {
		Base.add(this.model, this.getResource(), NEARBYPERSON, value);
	}
  

    /**
     * Sets a value of property NearbyPerson from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setNearbyPerson( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, NEARBYPERSON, value);
	}
	
    /**
     * Sets a value of property NearbyPerson from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setNearbyPerson( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), NEARBYPERSON, value);
	}
    /**
     * Sets a value of property NearbyPerson from an instance of Person 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setNearbyPerson(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.pimo.Person value) {
		Base.set(model, instanceResource, NEARBYPERSON, value);
	}
	
    /**
     * Sets a value of property NearbyPerson from an instance of Person 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setNearbyPerson(eu.dime.ps.semantic.model.pimo.Person value) {
		Base.set(this.model, this.getResource(), NEARBYPERSON, value);
	}
  


    /**
     * Removes a value of property NearbyPerson as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeNearbyPerson( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, NEARBYPERSON, value);
	}
	
    /**
     * Removes a value of property NearbyPerson as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeNearbyPerson( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), NEARBYPERSON, value);
	}
    /**
     * Removes a value of property NearbyPerson given as an instance of Person 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeNearbyPerson(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.pimo.Person value) {
		Base.remove(model, instanceResource, NEARBYPERSON, value);
	}
	
    /**
     * Removes a value of property NearbyPerson given as an instance of Person 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeNearbyPerson(eu.dime.ps.semantic.model.pimo.Person value) {
		Base.remove(this.model, this.getResource(), NEARBYPERSON, value);
	}
  
    /**
     * Removes all values of property NearbyPerson     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllNearbyPerson( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, NEARBYPERSON);
	}
	
    /**
     * Removes all values of property NearbyPerson	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllNearbyPerson() {
		Base.removeAll(this.model, this.getResource(), NEARBYPERSON);
	}
 }