/*
* Copyright 2013 by the digital.me project (http:\\www.dime-project.eu).
*
* Licensed under the EUPL, Version 1.1 only (the "Licence");
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
*
* http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and limitations under the Licence.
*/

package eu.dime.ps.semantic.model.dcon;

import org.ontoware.aifbcommons.collection.ClosableIterator;
import org.ontoware.rdf2go.exception.ModelRuntimeException;
import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.Base;
import org.ontoware.rdfreactor.runtime.ReactorResult;


/**
 * This class manages access to these properties:
 * <ul>
 *   <li> CurrentActivity </li>
 *   <li> CurrentAvailability </li>
 *   <li> CurrentMode </li>
 * </ul>
 *
 * class- This class was generated by <a href="http://RDFReactor.semweb4j.org">RDFReactor</a> */
public class State extends eu.dime.ps.semantic.model.dcon.Aspect {

    /** http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#State */
    @SuppressWarnings("hiding")
	public static final URI RDFS_CLASS = new URIImpl("http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#State", false);

    /** http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#currentActivity */
    @SuppressWarnings("hiding")
	public static final URI CURRENTACTIVITY = new URIImpl("http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#currentActivity",false);

    /** http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#currentAvailability */
    @SuppressWarnings("hiding")
	public static final URI CURRENTAVAILABILITY = new URIImpl("http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#currentAvailability",false);

    /** http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#currentMode */
    @SuppressWarnings("hiding")
	public static final URI CURRENTMODE = new URIImpl("http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#currentMode",false);

    /** 
     * All property-URIs with this class as domain.
     * All properties of all super-classes are also available. 
     */
    @SuppressWarnings("hiding")
    public static final URI[] MANAGED_URIS = {
      new URIImpl("http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#currentActivity",false),
      new URIImpl("http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#currentAvailability",false),
      new URIImpl("http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#currentMode",false) 
    };


	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.semweb4j.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier Resource that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c1] 
	 */
	protected State (Model model, URI classURI, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param instanceIdentifier an RDF2Go Resource identifying this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c2] 
	 */
	public State (Model model, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}


	/**
	 * Returns a Java wrapper over an RDF object, identified by a URI, given as a String.
	 * Creating two wrappers for the same URI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uriString a URI given as a String
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 * @throws ModelRuntimeException if URI syntax is wrong
	 *
	 * [Generated from RDFReactor template rule #c7] 
	 */
	public State (Model model, String uriString, boolean write) throws ModelRuntimeException {
		super(model, RDFS_CLASS, new URIImpl(uriString,false), write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c8] 
	 */
	public State (Model model, BlankNode bnode, boolean write) {
		super(model, RDFS_CLASS, bnode, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly generated URI.
	 * Creating two wrappers results in different URIs.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c9] 
	 */
	public State (Model model, boolean write) {
		super(model, RDFS_CLASS, model.newRandomUniqueURI(), write);
	}

    ///////////////////////////////////////////////////////////////////
    // typing

	/**
	 * Return an existing instance of this class in the model. No statements are written.
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return an instance of State  or null if none existst
	 *
	 * [Generated from RDFReactor template rule #class0] 
	 */
	public static State  getInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getInstance(model, instanceResource, State.class);
	}

	/**
	 * Create a new instance of this class in the model. 
	 * That is, create the statement (instanceResource, RDF.type, http://www.semanticdesktop.org/ontologies/2011/10/05/dcon#State).
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class1] 
	 */
	public static void createInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.createInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return true if instanceResource is an instance of this class in the model
	 *
	 * [Generated from RDFReactor template rule #class2] 
	 */
	public static boolean hasInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.hasInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as RDF resources
	 *
	 * [Generated from RDFReactor template rule #class3] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllInstances(Model model) {
		return Base.getAllInstances(model, RDFS_CLASS, org.ontoware.rdf2go.model.node.Resource.class);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as a ReactorResult,
	 * which can conveniently be converted to iterator, list or array.
	 *
	 * [Generated from RDFReactor template rule #class3-as] 
	 */
	public static ReactorResult<? extends State> getAllInstances_as(Model model) {
		return Base.getAllInstances_as(model, RDFS_CLASS, State.class );
	}

    /**
	 * Remove rdf:type State from this instance. Other triples are not affected.
	 * To delete more, use deleteAllProperties
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class4] 
	 */
	public static void deleteInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * Delete all (this, *, *), i.e. including rdf:type
	 * @param model an RDF2Go model
	 * @param resource
	 */
	public static void deleteAllProperties(Model model,	org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteAllProperties(model, instanceResource);
	}

    ///////////////////////////////////////////////////////////////////
    // property access methods

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as RDF resources, that have a relation 'State' to this State instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1static] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllState_Inverse(Model model, Object objectValue) {
		return Base.getAll_Inverse(model, eu.dime.ps.semantic.model.RDFReactorThing.STATE, objectValue);
	}

	/**
	 * @return all A's as RDF resources, that have a relation 'State' to this State instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1dynamic] 
	 */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllState_Inverse() {
		return Base.getAll_Inverse(this.model, eu.dime.ps.semantic.model.RDFReactorThing.STATE, this.getResource() );
	}

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as a ReactorResult, that have a relation 'State' to this State instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse-as1static] 
	 */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Resource> getAllState_Inverse_as(Model model, Object objectValue) {
		return Base.getAll_Inverse_as(model, eu.dime.ps.semantic.model.RDFReactorThing.STATE, objectValue, org.ontoware.rdf2go.model.node.Resource.class);
	}



    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@618693d1 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasCurrentActivity(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, CURRENTACTIVITY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@618693d1 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasCurrentActivity() {
		return Base.has(this.model, this.getResource(), CURRENTACTIVITY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@618693d1 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasCurrentActivity(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, CURRENTACTIVITY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@618693d1 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasCurrentActivity( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), CURRENTACTIVITY);
	}

     /**
     * Get all values of property CurrentActivity as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllCurrentActivity_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, CURRENTACTIVITY);
	}
	
    /**
     * Get all values of property CurrentActivity as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllCurrentActivity_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, CURRENTACTIVITY, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property CurrentActivity as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllCurrentActivity_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), CURRENTACTIVITY);
	}

    /**
     * Get all values of property CurrentActivity as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllCurrentActivity_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), CURRENTACTIVITY, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property CurrentActivity     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<eu.dime.ps.semantic.model.dpo.Activity> getAllCurrentActivity(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, CURRENTACTIVITY, eu.dime.ps.semantic.model.dpo.Activity.class);
	}
	
    /**
     * Get all values of property CurrentActivity as a ReactorResult of Activity 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<eu.dime.ps.semantic.model.dpo.Activity> getAllCurrentActivity_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, CURRENTACTIVITY, eu.dime.ps.semantic.model.dpo.Activity.class);
	}

    /**
     * Get all values of property CurrentActivity     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<eu.dime.ps.semantic.model.dpo.Activity> getAllCurrentActivity() {
		return Base.getAll(this.model, this.getResource(), CURRENTACTIVITY, eu.dime.ps.semantic.model.dpo.Activity.class);
	}

    /**
     * Get all values of property CurrentActivity as a ReactorResult of Activity 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<eu.dime.ps.semantic.model.dpo.Activity> getAllCurrentActivity_as() {
		return Base.getAll_as(this.model, this.getResource(), CURRENTACTIVITY, eu.dime.ps.semantic.model.dpo.Activity.class);
	}
 
    /**
     * Adds a value to property CurrentActivity as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addCurrentActivity(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, CURRENTACTIVITY, value);
	}
	
    /**
     * Adds a value to property CurrentActivity as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addCurrentActivity( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), CURRENTACTIVITY, value);
	}
    /**
     * Adds a value to property CurrentActivity from an instance of Activity 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addCurrentActivity(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.dpo.Activity value) {
		Base.add(model, instanceResource, CURRENTACTIVITY, value);
	}
	
    /**
     * Adds a value to property CurrentActivity from an instance of Activity 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addCurrentActivity(eu.dime.ps.semantic.model.dpo.Activity value) {
		Base.add(this.model, this.getResource(), CURRENTACTIVITY, value);
	}
  

    /**
     * Sets a value of property CurrentActivity from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setCurrentActivity( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, CURRENTACTIVITY, value);
	}
	
    /**
     * Sets a value of property CurrentActivity from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setCurrentActivity( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), CURRENTACTIVITY, value);
	}
    /**
     * Sets a value of property CurrentActivity from an instance of Activity 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setCurrentActivity(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.dpo.Activity value) {
		Base.set(model, instanceResource, CURRENTACTIVITY, value);
	}
	
    /**
     * Sets a value of property CurrentActivity from an instance of Activity 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setCurrentActivity(eu.dime.ps.semantic.model.dpo.Activity value) {
		Base.set(this.model, this.getResource(), CURRENTACTIVITY, value);
	}
  


    /**
     * Removes a value of property CurrentActivity as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeCurrentActivity( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, CURRENTACTIVITY, value);
	}
	
    /**
     * Removes a value of property CurrentActivity as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeCurrentActivity( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), CURRENTACTIVITY, value);
	}
    /**
     * Removes a value of property CurrentActivity given as an instance of Activity 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeCurrentActivity(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.dpo.Activity value) {
		Base.remove(model, instanceResource, CURRENTACTIVITY, value);
	}
	
    /**
     * Removes a value of property CurrentActivity given as an instance of Activity 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeCurrentActivity(eu.dime.ps.semantic.model.dpo.Activity value) {
		Base.remove(this.model, this.getResource(), CURRENTACTIVITY, value);
	}
  
    /**
     * Removes all values of property CurrentActivity     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllCurrentActivity( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, CURRENTACTIVITY);
	}
	
    /**
     * Removes all values of property CurrentActivity	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllCurrentActivity() {
		Base.removeAll(this.model, this.getResource(), CURRENTACTIVITY);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@4903c181 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasCurrentAvailability(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, CURRENTAVAILABILITY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@4903c181 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasCurrentAvailability() {
		return Base.has(this.model, this.getResource(), CURRENTAVAILABILITY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@4903c181 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasCurrentAvailability(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, CURRENTAVAILABILITY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@4903c181 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasCurrentAvailability( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), CURRENTAVAILABILITY);
	}

     /**
     * Get all values of property CurrentAvailability as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllCurrentAvailability_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, CURRENTAVAILABILITY);
	}
	
    /**
     * Get all values of property CurrentAvailability as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllCurrentAvailability_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, CURRENTAVAILABILITY, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property CurrentAvailability as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllCurrentAvailability_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), CURRENTAVAILABILITY);
	}

    /**
     * Get all values of property CurrentAvailability as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllCurrentAvailability_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), CURRENTAVAILABILITY, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property CurrentAvailability     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<eu.dime.ps.semantic.model.dpo.Availability> getAllCurrentAvailability(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, CURRENTAVAILABILITY, eu.dime.ps.semantic.model.dpo.Availability.class);
	}
	
    /**
     * Get all values of property CurrentAvailability as a ReactorResult of Availability 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<eu.dime.ps.semantic.model.dpo.Availability> getAllCurrentAvailability_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, CURRENTAVAILABILITY, eu.dime.ps.semantic.model.dpo.Availability.class);
	}

    /**
     * Get all values of property CurrentAvailability     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<eu.dime.ps.semantic.model.dpo.Availability> getAllCurrentAvailability() {
		return Base.getAll(this.model, this.getResource(), CURRENTAVAILABILITY, eu.dime.ps.semantic.model.dpo.Availability.class);
	}

    /**
     * Get all values of property CurrentAvailability as a ReactorResult of Availability 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<eu.dime.ps.semantic.model.dpo.Availability> getAllCurrentAvailability_as() {
		return Base.getAll_as(this.model, this.getResource(), CURRENTAVAILABILITY, eu.dime.ps.semantic.model.dpo.Availability.class);
	}
 
    /**
     * Adds a value to property CurrentAvailability as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addCurrentAvailability(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, CURRENTAVAILABILITY, value);
	}
	
    /**
     * Adds a value to property CurrentAvailability as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addCurrentAvailability( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), CURRENTAVAILABILITY, value);
	}
    /**
     * Adds a value to property CurrentAvailability from an instance of Availability 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addCurrentAvailability(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.dpo.Availability value) {
		Base.add(model, instanceResource, CURRENTAVAILABILITY, value);
	}
	
    /**
     * Adds a value to property CurrentAvailability from an instance of Availability 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addCurrentAvailability(eu.dime.ps.semantic.model.dpo.Availability value) {
		Base.add(this.model, this.getResource(), CURRENTAVAILABILITY, value);
	}
  

    /**
     * Sets a value of property CurrentAvailability from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setCurrentAvailability( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, CURRENTAVAILABILITY, value);
	}
	
    /**
     * Sets a value of property CurrentAvailability from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setCurrentAvailability( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), CURRENTAVAILABILITY, value);
	}
    /**
     * Sets a value of property CurrentAvailability from an instance of Availability 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setCurrentAvailability(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.dpo.Availability value) {
		Base.set(model, instanceResource, CURRENTAVAILABILITY, value);
	}
	
    /**
     * Sets a value of property CurrentAvailability from an instance of Availability 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setCurrentAvailability(eu.dime.ps.semantic.model.dpo.Availability value) {
		Base.set(this.model, this.getResource(), CURRENTAVAILABILITY, value);
	}
  


    /**
     * Removes a value of property CurrentAvailability as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeCurrentAvailability( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, CURRENTAVAILABILITY, value);
	}
	
    /**
     * Removes a value of property CurrentAvailability as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeCurrentAvailability( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), CURRENTAVAILABILITY, value);
	}
    /**
     * Removes a value of property CurrentAvailability given as an instance of Availability 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeCurrentAvailability(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.dpo.Availability value) {
		Base.remove(model, instanceResource, CURRENTAVAILABILITY, value);
	}
	
    /**
     * Removes a value of property CurrentAvailability given as an instance of Availability 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeCurrentAvailability(eu.dime.ps.semantic.model.dpo.Availability value) {
		Base.remove(this.model, this.getResource(), CURRENTAVAILABILITY, value);
	}
  
    /**
     * Removes all values of property CurrentAvailability     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllCurrentAvailability( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, CURRENTAVAILABILITY);
	}
	
    /**
     * Removes all values of property CurrentAvailability	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllCurrentAvailability() {
		Base.removeAll(this.model, this.getResource(), CURRENTAVAILABILITY);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@6c1d201c has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasCurrentMode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, CURRENTMODE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@6c1d201c has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasCurrentMode() {
		return Base.has(this.model, this.getResource(), CURRENTMODE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@6c1d201c has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasCurrentMode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, CURRENTMODE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@6c1d201c has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasCurrentMode( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), CURRENTMODE);
	}

     /**
     * Get all values of property CurrentMode as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllCurrentMode_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, CURRENTMODE);
	}
	
    /**
     * Get all values of property CurrentMode as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllCurrentMode_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, CURRENTMODE, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property CurrentMode as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllCurrentMode_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), CURRENTMODE);
	}

    /**
     * Get all values of property CurrentMode as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllCurrentMode_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), CURRENTMODE, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property CurrentMode     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<eu.dime.ps.semantic.model.ddo.Mode> getAllCurrentMode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, CURRENTMODE, eu.dime.ps.semantic.model.ddo.Mode.class);
	}
	
    /**
     * Get all values of property CurrentMode as a ReactorResult of Mode 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<eu.dime.ps.semantic.model.ddo.Mode> getAllCurrentMode_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, CURRENTMODE, eu.dime.ps.semantic.model.ddo.Mode.class);
	}

    /**
     * Get all values of property CurrentMode     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<eu.dime.ps.semantic.model.ddo.Mode> getAllCurrentMode() {
		return Base.getAll(this.model, this.getResource(), CURRENTMODE, eu.dime.ps.semantic.model.ddo.Mode.class);
	}

    /**
     * Get all values of property CurrentMode as a ReactorResult of Mode 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<eu.dime.ps.semantic.model.ddo.Mode> getAllCurrentMode_as() {
		return Base.getAll_as(this.model, this.getResource(), CURRENTMODE, eu.dime.ps.semantic.model.ddo.Mode.class);
	}
 
    /**
     * Adds a value to property CurrentMode as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addCurrentMode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, CURRENTMODE, value);
	}
	
    /**
     * Adds a value to property CurrentMode as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addCurrentMode( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), CURRENTMODE, value);
	}
    /**
     * Adds a value to property CurrentMode from an instance of Mode 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addCurrentMode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.ddo.Mode value) {
		Base.add(model, instanceResource, CURRENTMODE, value);
	}
	
    /**
     * Adds a value to property CurrentMode from an instance of Mode 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addCurrentMode(eu.dime.ps.semantic.model.ddo.Mode value) {
		Base.add(this.model, this.getResource(), CURRENTMODE, value);
	}
  

    /**
     * Sets a value of property CurrentMode from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setCurrentMode( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, CURRENTMODE, value);
	}
	
    /**
     * Sets a value of property CurrentMode from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setCurrentMode( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), CURRENTMODE, value);
	}
    /**
     * Sets a value of property CurrentMode from an instance of Mode 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setCurrentMode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.ddo.Mode value) {
		Base.set(model, instanceResource, CURRENTMODE, value);
	}
	
    /**
     * Sets a value of property CurrentMode from an instance of Mode 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setCurrentMode(eu.dime.ps.semantic.model.ddo.Mode value) {
		Base.set(this.model, this.getResource(), CURRENTMODE, value);
	}
  


    /**
     * Removes a value of property CurrentMode as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeCurrentMode( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, CURRENTMODE, value);
	}
	
    /**
     * Removes a value of property CurrentMode as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeCurrentMode( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), CURRENTMODE, value);
	}
    /**
     * Removes a value of property CurrentMode given as an instance of Mode 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeCurrentMode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, eu.dime.ps.semantic.model.ddo.Mode value) {
		Base.remove(model, instanceResource, CURRENTMODE, value);
	}
	
    /**
     * Removes a value of property CurrentMode given as an instance of Mode 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeCurrentMode(eu.dime.ps.semantic.model.ddo.Mode value) {
		Base.remove(this.model, this.getResource(), CURRENTMODE, value);
	}
  
    /**
     * Removes all values of property CurrentMode     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllCurrentMode( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, CURRENTMODE);
	}
	
    /**
     * Removes all values of property CurrentMode	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllCurrentMode() {
		Base.removeAll(this.model, this.getResource(), CURRENTMODE);
	}
 }